const CONFIG_EMAIL_TMPL = 'Olá, <strong>{0}</strong>, seja bem vindo à Node Store!';
const CONFIG_SALT_CRIPT_KEY = 'f5b99242-6504-4ca3';
const CONFIG_MONGO_CONN_STRING = 'mongodb://localhost:27017/course';
const CONFIG_EMAIL_SEND_GRID = 'SUA CHAVE';
const CONFIG_CONTAINNER_CONN_STRING= 'SUA CONNECTION STRING';
const CONFIG_EMAIL_SMTP = '';

module.exports = {
    CONFIG_SALT_CRIPT_KEY,
    CONFIG_MONGO_CONN_STRING,
    CONFIG_EMAIL_SEND_GRID,
    CONFIG_CONTAINNER_CONN_STRING,
    CONFIG_EMAIL_TMPL
}